PrimerNetCoreMvc/Models/ErrorViewModel.cs
using System;

namespace PrimerNetCoreMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerNetCoreMvc/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerNetCoreMvc.Models
{
    public class Persona
    {
        public String Nombre { get; set; }
        public int Edad { get; set; }
        public String Email { get; set; }
    }
}

PrimerNetCoreMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PrimerNetCoreMvc.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerNetCoreMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerNetCoreMvc/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerNetCoreMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerNetCoreMvc.Controllers
{
    public class InformacionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ControladorVista()
        {
            //ViewData["Nombre"] = "Alumno";
            //ViewData["Edad"] = 28;

            Persona person = new Persona();
            person.Nombre = "Persona Model";
            person.Edad = 44;
            person.Email = "personamodel@gmail.com";
            return View(person);
        }

        public IActionResult VistaControllerGet
            (string app, int version)
        {
            ViewData["DATOS"] = app + ", Versión: " + version;
            return View();
        }

        //METODO GET
        public IActionResult VistaPost()
        {
            return View();
        }

        //METODO POST
        [HttpPost]
        public IActionResult VistaPost
            (Persona persona)
        {
            return View(persona);
        }

        //GET VistaNumeroDoble
        public IActionResult VistaNumeroDoble(int numero)
        {
            int doble = numero * 2;
            ViewBag.Doble = "El doble del número es: " + doble;
            return View();
        }
    }
}

PrimerNetCoreMvc/Controllers/OtroController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerNetCoreMvc.Controllers
{
    public class OtroController : Controller
    {
        public IActionResult Indexa()
        {
            return View();
        }
    }
}

PrimerNetCoreMvc/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerNetCoreMvc.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult PrimeraPagina()
        {
            return View();
        }
    }
}

PrimerNetCoreMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrimerNetCoreMvc/Views/Informacion/ControladorVista.cshtml
@model Persona 

<h1>Información recibida</h1>

<h1 style="color:red;background-color:yellow">
    @Model.Nombre, Edad: @Model.Edad, Email: @Model.Email
</h1>

<h2 style="color:blue">
    Su nombre es @ViewBag.Nombre y su edad es @ViewData["Edad"]
</h2>

PrimerNetCoreMvc/Views/Informacion/Index.cshtml
<h1>Menú información entre componentes</h1>

<ul class="list-group">
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="ControladorVista">
            Información controlador vista
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="VistaControllerGet"
           asp-route-app="Net Core Mvc"
           asp-route-version="5">
            Información GET Vista Controller
        </a>
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Información GET Vista Controller"
       , "VistaControllerGet", "Informacion",
       new { app = "Net Core", version = 5 })
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="VistaPost">
            Enviar información POST
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="VistaNumeroDoble"
           asp-route-numero="7">
            Número doble 7
        </a>
    </li>
</ul>

PrimerNetCoreMvc/Views/Informacion/VistaControllerGet.cshtml
<h1>Información GET Vista Controller</h1>

<h1 style="color:blue">
    @ViewData["DATOS"]
</h1>

PrimerNetCoreMvc/Views/Informacion/VistaNumeroDoble.cshtml
<h1>Parámetros opcionales Action</h1>

<h2 style="color:blue">@ViewBag.Doble</h2>

PrimerNetCoreMvc/Views/Informacion/VistaPost.cshtml
@model Persona

<h1>Información con POST</h1>

<form method="post">
    <label>Nombre: </label>
    <input type="text" name="nombre"
           class="form-control" /><br />
    <label>Edad: </label>
    <input type="text" name="edad"
           class="form-control" /><br />
    <label>Email: </label>
    <input type="text" name="email"
           class="form-control" /><br />
    <button type="submit" class="btn-info">
        Enviar información
    </button>
</form>
@if (Model != null)
{
    <h1 style="color:blue">
        Nombre: @Model.Nombre, Edad: @Model.Edad
    </h1>
    <h2 style="color:red">
        Email: @Model.Email
    </h2>
}

PrimerNetCoreMvc/Views/Otro/Index.cshtml
<h1>Index otro</h1>

PrimerNetCoreMvc/Views/Prueba/PrimeraPagina.cshtml
<h1>Mi primera página MVC Net Core</h1>

@*
COMENTARIOS EN RAZOR    
*@

DECLARACION DE VARIABLES EN RAZOR
@{ 
    //ESTAS VARIABLES SON LOCALES EN LA PAGINA
    int valor = 14;
    String texto = "Variable a nivel de página";
    //CODIGO PURO C#
    valor += 1;
    texto += ", hoy es Martes";
    int numero = 1;
}

DIBUJAR VARIABLES
<h1 style="color:red">@texto</h1>

CODIGO LOGICO
@if (numero > 0)
{
    //TODO ESTO ES C#
    <h1 style="color:blue">POSITIVO: @numero</h1>
}
else
{
    //TODO ESTO ES C#
    <h1 style="color:orange">NEGATIVO: @numero</h1>
}

@for (int i = 1; i <= 6; i++) { 
    <h1>Esto es HTML</h1>
}

PrimerNetCoreMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerNetCoreMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" 
                   asp-action="Index">PrimerNetCoreMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Informacion"
                               asp-action="Index">
                                Información
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <a asp-controller="Prueba" asp-action="PrimeraPagina">
                Mi primera pagina
            </a>
            <a asp-controller="Otro" asp-action="Index">
                Otro controller
            </a>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PrimerNetCoreMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>